### PR TITLE
QModManager 3.0.2

### PR DESCRIPTION
**Pull request by MrPurple6411**
# QModManager 3.0.2
-  Fixed file corruption issue when installing for the Unity 2019 version of BelowZero
-  Fixed Unhandled Exceptions when missing Dependencies
-  Improved Logging system to better show what is missing
-  Fixed Unhandled Exceptions when a mod is installed more then once.

[Release Files](https://github.com/SubnauticaModding/QModManager/tree/BelowZero_AudioFixer/Build)

### CODE REVIEW

**Comment by AlexejheroYTB** [comment]
I say this should be merged into dev, and not directly into master

**Comment by MrPurple6411** [comment]
if we put it into dev then it will have to wait till we are ready to release 3.1 if we do it in master then people who have BZ mods can start work on fixing for when experimental hits stable. otherwise it will break a LOT and we will be stuck scrambling again.

**Comment by AlexejheroYTB** [comment]
Merging this pull request will trigger an update notification for everyone when they launch the game. Make sure that this version is ready to be released before merging this pr.

**Comment by AlexejheroYTB** [comment]
@PrimeSonic So, what're we doing with this PR?

**Comment by PrimeSonic** [comment]
> @PrimeSonic So, what're we doing with this PR?

@AlexejheroYTB  Still waiting on this Pull Request to be finished first before we release a 3.0.2 version for BZ and Sub
https://github.com/SubnauticaModding/QModManager/pull/131

@MrPurple6411 Do you agree?

**Comment by MrPurple6411** [comment]
QModManager 3.0.2
- Fixed file corruption issue when installing for the Unity 2019 version of BelowZero
- Fixed Unhandled Exceptions when missing Dependencies
- Improved Logging system to better show what is missing
- Fixed Unhandled Exceptions when a mod is installed more then once.

**Pull request merged**
